package main

import (
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"strings"
)

func main() {
	dir := "keys"
	fs, _ := ioutil.ReadDir(dir)
	out, _ := os.Create("shell/keys.go")
	out.Write([]byte("package shell \n\n// autogenerated - do not modify\n\nconst (\n"))
	for _, f := range fs {
		print(f)
		out.Write([]byte(strings.ReplaceAll(f.Name(), ".", "_") + " = `"))
		f, _ := os.Open(fmt.Sprintf("%s/%s", dir, f.Name()))
		io.Copy(out, f)
		out.Write([]byte("`\n"))
	}
	out.Write([]byte(")\n"))
}
